# Generated by Django 5.1.4 on 2024-12-28 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formtemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='formfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('radio', 'Radio button'), ('textarea', 'Text Area'), ('dropdown', 'drop-down'), ('number', 'number'), ('img', 'img')], max_length=20)),
                ('options', models.TextField(blank=True, help_text='comma-separated options', null=True)),
                ('order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_builder.formtemplate')),
            ],
        ),
    ]
