# Generated by Django 5.1.4 on 2024-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
