# Generated by Django 5.1.4 on 2024-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_formtemplate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('radio', 'Radio button'), ('textarea', 'Text Area'), ('dropdown', 'drop-down'), ('number', 'number')], max_length=20),
        ),
    ]
