# Generated by Django 5.1.4 on 2024-12-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_alter_formfield_label_alter_formfield_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area'), ('dropdown', 'drop-down'), ('number', 'number')], max_length=20),
        ),
    ]
